### ISSUE TITLE
Create Ingestion Pipeline Between MTH5 Experiments and IRIS miniseed respository

### ISSUE THREAD

**Issue by timronan** [kujaku11/mth5#99]
A protocol will need to be developed to ingest MTH5 data into the IRIS miniseed archive. It seems possible to extract data from MTH5 repositories as miniseed and to load this extracted miniseed into the IRIS miniseed repository using the [miniseed2dmc](https://github.com/iris-edu/miniseed2dmc) protocol. 

This pipeline will need further discussion and testing, but I wanted to post this enhancement suggestion while the idea was still fresh.

**Comment by kujaku11** [comment]
The pipeline would be:

1. Create StationXML of the metadata and submit to IRIS
2. Output the data as miniSEED,  using tools built-in to `mth5.timeseries.ChannelTS` and use miniseed2dmc tool

**Comment by kkappler** [comment]
A good test for this would be to combine the task with aurora issue issue159 [https://github.com/simpeg/aurora/issues/159](url)

If you run  ```aurora/tests/parkfield/make_parkfield_mth5.py``` then two h5s will appear:

> aurora/tests/parkfield/data/pkd_sao_test_00.h5

> aurora/tests/parkfield/data/pkd_test_00.h5

These fully formed h5 files will have all the metadata and data time series that would need to be stored at IRIS so that we can remove the NCEDC server dependency from the aurora tests.

**Comment by kujaku11** [comment]
MakeMTH5.FDSN solves this.
